# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClassName: kgateway

  listeners:
    - name: http
      protocol: HTTP
      port: 80

      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - group: ""
          kind: Service
          name: frontend
          port: 80
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: productcatalogservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.ProductCatalogService/

      backendRefs:
        - group: ""
          kind: Service
          name: productcatalogservice
          port: 3550
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: currencyservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.CurrencyService/

      backendRefs:
        - group: ""
          kind: Service
          name: currencyservice
          port: 7000
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cartservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.CartService/

      backendRefs:
        - group: ""
          kind: Service
          name: cartservice
          port: 7070
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: recommendationservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.RecommendationService/

      backendRefs:
        - group: ""
          kind: Service
          name: recommendationservice
          port: 8080
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shippingservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.ShippingService/

      backendRefs:
        - group: ""
          kind: Service
          name: shippingservice
          port: 50051
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: checkoutservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.CheckoutService/

      backendRefs:
        - group: ""
          kind: Service
          name: checkoutservice
          port: 5050
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adservice-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
      namespace: default
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /hipstershop.AdService/

      backendRefs:
        - group: ""
          kind: Service
          name: adservice
          port: 9555
          weight: 1